services:
  backend:
    image: ghcr.io/alinazolotavina/znac-project-backend:latest
    restart: unless-stopped
    expose:
      - "4000"
    env_file:
      - ./znac-api/.env.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: ghcr.io/alinazolotavina/znac-project-nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - backend
